# Generated by Django 4.0.4 on 2022-05-27 15:50

import Teacher.models
import django.core.validators
from django.db import migrations, models
import utils.validator


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='resume_file',
            field=models.FileField(blank=True, help_text='لطفا فایل رزمه خود را در قالب یکی از پسوند های (jpg,png,txt,docx,doc,pdf) آپلود کنید.', null=True, upload_to=Teacher.models.upload_resume_file, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'txt', 'doc', 'docx', 'pdf']), utils.validator.validate_file_size], verbose_name='فایل رزمه'),
        ),
    ]
