# Generated by Django 4.0.4 on 2022-06-23 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_alter_teacher_created_at_alter_teacher_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='مثال: ۰۱۵۶۳۵۳۰۱۱', max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(16), django.core.validators.RegexValidator('[\\d۱۲۳۴۵۶۷۸۹۰]{6,18}')], verbose_name='شماره حساب بانکی'),
        ),
    ]
