# Generated by Django 4.0.4 on 2022-10-18 20:40

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0004_teacher_bank_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('amount', models.CharField(max_length=255, verbose_name='مبلغ')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendances', to='Teacher.teacher', verbose_name='استاد')),
            ],
            options={
                'verbose_name': 'پرداختی مدرس',
                'verbose_name_plural': 'پرداختی مدرس ها',
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('desc', models.TextField(verbose_name='توضیح')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_payments', to='Teacher.teacher', verbose_name='استاد')),
            ],
            options={
                'verbose_name': 'حضور و غیاب مدرس',
                'verbose_name_plural': 'حضور و غیاب مدرس ها',
            },
        ),
    ]
