# Generated by Django 4.0.4 on 2022-06-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Installment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinstallmentpayments',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='مبلغ'),
        ),
    ]
