# Generated by Django 4.0.4 on 2022-06-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Installment', '0002_alter_userinstallmentpayments_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinstallmentpayments',
            name='amount',
            field=models.PositiveBigIntegerField(verbose_name='مبلغ'),
        ),
    ]
