# Generated by Django 4.0.4 on 2022-08-27 14:51

import QuizBuilder.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Class', '0011_remove_classuser_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('desc', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('open', 'باز'), ('close', 'بسته')], default='open', max_length=50, verbose_name='وضعیت')),
                ('time', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان آزمون (دقیقه)')),
                ('expire_time', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان آزمون')),
                ('class_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='Class.class', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': 'آزمون ها',
            },
            bases=(QuizBuilder.mixins.QuizStartedSmsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('description', models.TextField(verbose_name='متن سوال')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='بارم')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('text', models.CharField(max_length=256, verbose_name='متن جواب')),
                ('is_answer', models.BooleanField(default=False, verbose_name='جواب صحیح است؟')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('status', models.CharField(choices=[('pending', 'در حال انجام'), ('done', 'انجام شده'), ('pass', 'پاس شده'), ('fail', 'رد شده')], default='pending', max_length=255, verbose_name='وضعیت')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع آزمون')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='نمره(بارم)')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quizzes', to='QuizBuilder.quiz', verbose_name='آزمون')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserQuizQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizBuilder.quizquestionchoice', verbose_name='پاسخ کاربر')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizBuilder.quizquestion', verbose_name='سوال')),
                ('user_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz_questions', to='QuizBuilder.userquiz', verbose_name='پاسخنامه کاربر')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='choices',
            field=models.ManyToManyField(to='QuizBuilder.quizquestionchoice', verbose_name='گزینه های سوال'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='QuizBuilder.quiz', verbose_name='آزمون'),
        ),
    ]
