# Generated by Django 4.0.4 on 2022-05-28 08:52

import Course.models
from django.db import migrations, models
import django.db.models.deletion
import utils.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teacher', '0002_teacher_resume_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('desc', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('amount', models.PositiveIntegerField(verbose_name='قیمت')),
                ('users_limit', models.PositiveIntegerField(verbose_name='تعداد مجاز شرکت کنندگان')),
                ('cover', models.ImageField(blank=True, help_text='عکس (کاور) دوره را آپلود کنید.', null=True, upload_to=Course.models.upload_cover_file, validators=[utils.validator.validate_file_size], verbose_name='عکس (کاور)')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Teacher.teacher', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
            },
        ),
    ]
