# Generated by Django 4.0.4 on 2022-05-28 09:41

import Course.models
from django.db import migrations, models
import django.db.models.deletion
import utils.validator


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_teacher_resume_file'),
        ('Course', '0002_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.ImageField(default='', upload_to=Course.models.upload_cover_file, validators=[utils.validator.validate_file_size], verbose_name='عکس (کاور)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Teacher.teacher', verbose_name='مدرس'),
        ),
    ]
