# Generated by Django 4.0.4 on 2022-05-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_alter_course_cover_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'در انتظار'), ('published', 'منتشر شده'), ('finished', 'پایان یافته')], default='draft', max_length=50, verbose_name='وضعیت'),
        ),
    ]
