# Generated by Django 4.0.4 on 2022-05-28 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_teacher_resume_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Course', '0004_alter_course_amount_alter_course_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('deactive', 'غیرفعال')], default='draft', max_length=50, verbose_name='وضعیت')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='Teacher.teacher', verbose_name='دوره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دوره ی کاربران',
                'verbose_name_plural': 'دوره ی کاربران ها',
            },
        ),
    ]
