# Generated by Django 4.0.4 on 2022-05-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_courseuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseuser',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('deactive', 'غیرفعال')], default='active', max_length=50, verbose_name='وضعیت'),
        ),
    ]
