# Generated by Django 4.0.4 on 2022-05-28 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_alter_courseuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuser',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع'),
            preserve_default=False,
        ),
    ]
