# Generated by Django 4.0.4 on 2022-05-28 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_courseuser_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseuser',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='Course.course', verbose_name='دوره'),
        ),
    ]
