# Generated by Django 4.0.4 on 2022-05-29 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0008_alter_courseuser_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseuser',
            name='start_date',
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع'),
            preserve_default=False,
        ),
    ]
