# Generated by Django 4.0.4 on 2022-05-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0009_remove_courseuser_start_date_course_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseuser',
            options={'verbose_name': 'دوره های کاربران', 'verbose_name_plural': 'دوره های کاربران ها'},
        ),
    ]
