# Generated by Django 4.0.4 on 2022-08-28 10:01

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('desc', models.TextField(max_length=500, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'متون راهنما',
                'verbose_name_plural': 'متون راهنما',
            },
        ),
    ]
