# Generated by Django 4.0.4 on 2022-06-11 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('gateway', models.CharField(choices=[('zarinpal', 'زرین پال')], default='', max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'در حال انتظار'), ('success', 'موفقیت\u200cآمیز'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=10)),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True)),
                ('authority', models.CharField(blank=True, max_length=255, null=True)),
                ('item_type', models.CharField(blank=True, choices=[('shop', 'فروشگاه'), ('class', 'شهریه کلاس')], max_length=40, null=True, verbose_name='نوع آیتم')),
                ('item_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه آیتم')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تراکنش درگاه پرداخت',
                'verbose_name_plural': 'تراکنش های درگاه پرداخت',
            },
        ),
    ]
