# Generated by Django 4.0.4 on 2022-06-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='item_type',
            field=models.CharField(blank=True, choices=[('shop', 'فروشگاه'), ('class', 'شهریه کلاس'), ('installment', 'قسط شهریه کلاس')], max_length=40, null=True, verbose_name='نوع آیتم'),
        ),
    ]
