# Generated by Django 4.0.4 on 2022-08-30 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Class', '0012_class_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('certify_that', models.CharField(blank=True, max_length=255, null=True, verbose_name='This is to certify that')),
                ('avarded', models.CharField(blank=True, max_length=255, null=True, verbose_name='has been avarded')),
                ('in_the', models.CharField(blank=True, max_length=255, null=True, verbose_name='in the')),
                ('on', models.CharField(blank=True, max_length=255, null=True, verbose_name='on')),
                ('place_of_Entry', models.CharField(blank=True, max_length=255, null=True, verbose_name='place of Entry')),
                ('refrence_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Refrence Number')),
                ('proudly_presented', models.CharField(blank=True, max_length=255, null=True, verbose_name='This certificate is proudly presented to')),
                ('completed_term', models.CharField(blank=True, max_length=255, null=True, verbose_name='having successfully completed a term of ?')),
                ('class_attendance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Class Attendance')),
                ('class_activity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Class Activity')),
                ('homework', models.CharField(blank=True, max_length=255, null=True, verbose_name='Homework')),
                ('workbook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Workbook')),
                ('listening', models.CharField(blank=True, max_length=255, null=True, verbose_name='Listening')),
                ('speaking', models.CharField(blank=True, max_length=255, null=True, verbose_name='Speaking')),
                ('reading', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reading')),
                ('writing', models.CharField(blank=True, max_length=255, null=True, verbose_name='Writing')),
                ('midterm_score', models.CharField(blank=True, max_length=255, null=True, verbose_name='Midterm Score')),
                ('final_exam', models.CharField(blank=True, max_length=255, null=True, verbose_name='Final Exam')),
                ('oral_score', models.CharField(blank=True, max_length=255, null=True, verbose_name='Oral Score')),
                ('overall', models.CharField(blank=True, max_length=255, null=True, verbose_name='Overall')),
                ('exam_status', models.CharField(blank=True, choices=[('pass', 'pass'), ('cp', 'cp'), ('fail', 'fail')], max_length=255, null=True, verbose_name='Overall')),
                ('date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Overall')),
                ('type', models.CharField(choices=[('ttc', 'TTC'), ('mock', 'MOCK'), ('term', 'ترمی')], max_length=255, verbose_name='نوع کارنامه')),
                ('class_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='Class.class', verbose_name='کلاس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کارنامه',
                'verbose_name_plural': 'کارنامه ها',
            },
        ),
    ]
