# Generated by Django 4.0.4 on 2022-08-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportCard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='exam_status',
            field=models.CharField(blank=True, choices=[('pass', 'PASS'), ('cp', 'C.P.'), ('fail', 'FAIL')], max_length=255, null=True, verbose_name='Exam Status'),
        ),
    ]
