# Generated by Django 4.0.4 on 2022-08-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReportCard', '0003_alter_reportcard_date_alter_reportcard_exam_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcard',
            old_name='place_of_Entry',
            new_name='place_of_entry',
        ),
    ]
