# Generated by Django 4.0.4 on 2022-09-05 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReportCard', '0004_rename_place_of_entry_reportcard_place_of_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcard',
            old_name='avarded',
            new_name='awarded',
        ),
    ]
