# Generated by Django 4.0.4 on 2022-10-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportCard', '0005_rename_avarded_reportcard_awarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='awarded',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='has been awarded'),
        ),
    ]
