# Generated by Django 4.0.4 on 2022-10-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportCard', '0006_alter_reportcard_awarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='completed_term',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='having successfully completed a term of'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Date'),
        ),
    ]
