# Generated by Django 4.0.4 on 2022-11-16 14:22

from django.db import migrations, models
import utils.validator


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_alter_chatmessage_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='chats', validators=[utils.validator.validate_file_size], verbose_name='فایل پیام'),
        ),
    ]
