# Generated by Django 4.0.4 on 2022-11-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_chatmessage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='متن پیام'),
        ),
    ]
