# Generated by Django 4.0.4 on 2022-08-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='is_accept',
            field=models.BooleanField(default=False, verbose_name='آیا تایید شده است؟'),
        ),
    ]
