# Generated by Django 4.0.4 on 2022-08-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_blogcomment_is_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='text',
            field=models.TextField(default='', verbose_name='متن'),
            preserve_default=False,
        ),
    ]
