# Generated by Django 4.0.4 on 2022-08-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_blogcomment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='text',
            field=models.TextField(max_length=150, verbose_name='متن'),
        ),
    ]
