# Generated by Django 4.0.4 on 2022-06-04 13:16

import Shop.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import utils.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('desc', models.TextField(verbose_name='توضیحات')),
                ('amount', models.PositiveIntegerField(verbose_name='قیمت')),
                ('discount_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت تخفیفی')),
                ('image', models.ImageField(upload_to=Shop.models.upload_image, validators=[utils.validator.validate_file_size], verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'محصول(خدمات) فروشی',
                'verbose_name_plural': 'محصول(خدمات) فروشی ها',
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='Shop.product', verbose_name='محصول(خدمت)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله ها',
            },
        ),
    ]
