# Generated by Django 4.0.4 on 2022-06-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='pay_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ پرداختی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت تخفیفی (تومان)'),
        ),
    ]
