# Generated by Django 4.0.4 on 2022-06-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_userproduct_pay_amount_alter_product_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproduct',
            options={'verbose_name': 'محصولات کاربران', 'verbose_name_plural': 'محصولات کاربران ها'},
        ),
    ]
