# Generated by Django 4.0.4 on 2022-08-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='-', max_length=255, verbose_name='نامک (slug)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='-', max_length=255, verbose_name='نامک (slug)'),
            preserve_default=False,
        ),
    ]
