# Generated by Django 4.0.4 on 2022-08-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی محصول', 'verbose_name_plural': 'دسته بندی محصول ها'},
        ),
    ]
