# Generated by Django 4.0.4 on 2022-08-30 21:31

import Shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.ImageField(blank=True, help_text='این فیلد برای محصولاتی است که بصورت فایلی و دانلودی هستند. اگر محصول شما دانلودی نیست این قسمت را خالی بگذارید.', null=True, upload_to=Shop.models.upload_image, verbose_name='فایل'),
        ),
    ]
