# Generated by Django 4.0.4 on 2022-10-16 11:07

import Shop.models
from django.db import migrations, models
import utils.validator


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=Shop.models.upload_gallery_image, validators=[utils.validator.validate_file_size], verbose_name='عکس'),
        ),
    ]
