# Generated by Django 4.0.4 on 2022-06-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slider', '0002_alter_slider_created_at_alter_slider_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='text',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='متن'),
        ),
    ]
