# Generated by Django 4.0.4 on 2022-08-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slider', '0003_slider_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.URLField(max_length=255, null=True, verbose_name='لینک'),
        ),
    ]
