# Generated by Django 4.0.4 on 2022-10-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_student_intro_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='intro_method',
        ),
    ]
