# Generated by Django 4.0.4 on 2022-05-22 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('code', models.CharField(max_length=6, verbose_name='کد')),
                ('is_used', models.BooleanField(default=False, verbose_name='آیا استفاده شده است')),
                ('type', models.CharField(choices=[('verify', 'تایید حساب کاربری'), ('reset_password', 'بازیابی رمز عبور')], default='verify', max_length=128, verbose_name='نوع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کد یکبار مصرف',
                'verbose_name_plural': 'کد ها یکبار مصرف',
            },
        ),
    ]
