# Generated by Django 4.0.4 on 2022-05-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='type',
        ),
    ]
