# Generated by Django 4.0.4 on 2022-05-31 10:08

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0003_alter_class_created_at_alter_class_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='start_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='classattendance',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ'),
        ),
    ]
