# Generated by Django 4.0.4 on 2022-06-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0004_alter_class_start_date_alter_classattendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='start_date',
        ),
        migrations.AddField(
            model_name='class',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان پایان کلاس'),
        ),
        migrations.AddField(
            model_name='class',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان شروع کلاس'),
        ),
    ]
