# Generated by Django 4.0.4 on 2022-06-03 11:55

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0005_remove_class_start_date_class_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classuser',
            name='payment_date',
            field=django_jalali.db.models.jDateField(blank=True, help_text='این فیلد برای هنرجویانی است که قرار است شهریه کلاس را در تاریخ مد نظر شما وارد کنند.', null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
