# Generated by Django 4.0.4 on 2022-06-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0006_classuser_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='status',
            field=models.CharField(choices=[('pending', 'انتظار'), ('active', 'فعال'), ('deactive', 'غیرفعال')], default='active', max_length=50, verbose_name='وضعیت'),
        ),
    ]
