# Generated by Django 4.0.4 on 2022-06-22 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Class', '0007_alter_class_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('payment_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='سقف تاریخ پرداخت')),
                ('is_complete', models.BooleanField(default=False, verbose_name='آیا کامل شده است؟')),
                ('class_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='Class.class', verbose_name='کلاس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'قسط پرداختی شهریه کلاس ها',
                'verbose_name_plural': 'قسط پرداختی شهریه کلاس ها',
            },
        ),
        migrations.CreateModel(
            name='UserInstallmentPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('amount', models.IntegerField(verbose_name='مبلغ')),
                ('is_payment', models.BooleanField(default=False, verbose_name='آیا پرداخت شده است؟')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='Class.userinstallment', verbose_name='قسط')),
            ],
            options={
                'verbose_name': 'قسط پرداختی شهریه کلاس ها',
                'verbose_name_plural': 'قسط پرداختی شهریه کلاس ها',
            },
        ),
    ]
