# Generated by Django 4.0.4 on 2022-06-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0008_userinstallment_userinstallmentpayments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinstallmentpayments',
            name='installment',
        ),
        migrations.DeleteModel(
            name='UserInstallment',
        ),
        migrations.DeleteModel(
            name='UserInstallmentPayments',
        ),
    ]
