# Generated by Django 4.0.4 on 2022-06-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0009_remove_userinstallmentpayments_installment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='amount',
            field=models.PositiveBigIntegerField(verbose_name='شهریه (تومان)'),
        ),
    ]
