# Generated by Django 4.0.4 on 2022-06-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0010_alter_class_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classuser',
            name='payment_date',
        ),
    ]
