# Generated by Django 4.0.4 on 2022-08-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0011_remove_classuser_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, verbose_name='نامک (slug)'),
        ),
    ]
