# Generated by Django 4.0.4 on 2022-08-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0012_class_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='classuser',
            name='adobe_connect_link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک ادوب کانکت'),
        ),
        migrations.AddField(
            model_name='classuser',
            name='adobe_connect_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رمزعبور ادوب کانکت'),
        ),
        migrations.AddField(
            model_name='classuser',
            name='adobe_connect_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام کاربری ادوب کانکت'),
        ),
    ]
