# Generated by Django 4.0.4 on 2022-10-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0013_classuser_adobe_connect_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classuser',
            name='adobe_connect_password',
        ),
        migrations.RemoveField(
            model_name='classuser',
            name='adobe_connect_username',
        ),
        migrations.AddField(
            model_name='classuserattendance',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات'),
        ),
    ]
