# Generated by Django 4.0.4 on 2022-10-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0014_remove_classuser_adobe_connect_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_show_in_slider',
            field=models.BooleanField(default=False, verbose_name='آیا در صفحه اصلی نمایش داده شود؟'),
        ),
        migrations.AddField(
            model_name='class',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='ایا ویژه است؟'),
        ),
    ]
