# Generated by Django 4.0.4 on 2022-11-03 21:06

import Class.mixins
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0015_class_is_show_in_slider_class_is_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(Class.mixins.ClassStartedSmsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='class',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='Class.category', verbose_name='دسته بندی'),
        ),
    ]
