# Generated by Django 4.0.4 on 2022-11-03 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0016_category_class_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی کلاس', 'verbose_name_plural': 'دسته بندی کلاس ها'},
        ),
    ]
