# Generated by Django 4.0.4 on 2022-11-12 21:39

from django.db import migrations, models
import utils.validator


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0017_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='categories', validators=[utils.validator.validate_file_size], verbose_name='عکس (کاور)'),
        ),
    ]
