# Generated by Django 4.0.4 on 2022-05-25 21:59

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_user_avatar_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/admin_panel/assets/img/user.jpg', null=True, upload_to=User.models.upload_avatar, verbose_name='عکس پروفایل'),
        ),
    ]
