# Generated by Django 4.0.4 on 2022-05-25 22:10

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=User.models.upload_avatar, verbose_name='عکس پروفایل'),
        ),
    ]
