# Generated by Django 4.0.4 on 2022-05-26 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='user',
            name='education_level',
            field=models.CharField(blank=True, choices=[('S', 'ابتدایی'), ('FH', 'متوسطه اول'), ('SH', 'متوسطه دوم'), ('UV', 'دانشگاه'), ('O', 'سایر')], max_length=128, null=True, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='نام پدر'),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='پایه تحصیلی'),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'مجرد'), ('M', 'متاهل')], max_length=128, null=True, verbose_name='وضعیت تاهل'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='شناسه ملی معتبر نیست.', regex='^\\d{10}$')], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام خانوادگی'),
        ),
    ]
