# Generated by Django 4.0.4 on 2022-08-26 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_alter_user_created_at_alter_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(default='', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='شناسه ملی معتبر نیست.', regex='^\\d{10}$')], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل معتبر نیست.', regex='(^\\+?(09|98|0)?(9([0-9]{9}))$)')], verbose_name='شماره موبایل'),
        ),
    ]
