# Generated by Django 4.0.4 on 2022-10-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education_level',
            field=models.CharField(blank=True, choices=[('S', 'ابتدایی'), ('FH', 'متوسطه اول'), ('SH', 'متوسطه دوم'), ('AD', 'کاردانی'), ('M', 'کارشناسی'), ('O', 'سایر')], max_length=128, null=True, verbose_name='مقطع تحصیلی'),
        ),
    ]
