# Generated by Django 4.0.4 on 2022-10-17 14:02

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Class', '0014_remove_classuser_adobe_connect_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('is_approved', models.BooleanField(default=False, verbose_name='وضعیت فعال')),
                ('class_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='Class.class', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'فرم نظرسنجی',
                'verbose_name_plural': 'فرم نظرسنجی ها',
            },
        ),
    ]
