# Generated by Django 4.0.4 on 2022-10-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0005_userpoll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpoll',
            options={'verbose_name': 'پاسخ فرم نظرسنجی', 'verbose_name_plural': 'پاسخ فرم نظرسنجی ها'},
        ),
        migrations.RenameField(
            model_name='userpoll',
            old_name='desc',
            new_name='text',
        ),
    ]
