# Generated by Django 4.0.4 on 2022-10-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0006_alter_userpoll_options_rename_desc_userpoll_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpoll',
            name='text',
        ),
        migrations.RemoveField(
            model_name='userpoll',
            name='title',
        ),
        migrations.AddField(
            model_name='userpoll',
            name='Information_and_guidance',
            field=models.CharField(choices=[('excellent', 'عالی'), ('good', 'خوب'), ('medium', 'متوسط'), ('weak', 'ضعیف')], max_length=255, null=True, verbose_name='اطلاع رسانی و راهنمایی لازم بصورت شفاف و دقیق'),
        ),
        migrations.AddField(
            model_name='userpoll',
            name='arrivals_and_departures',
            field=models.CharField(choices=[('excellent', 'عالی'), ('good', 'خوب'), ('medium', 'متوسط'), ('weak', 'ضعیف')], max_length=255, null=True, verbose_name='ورود و خروج به موقع به کلاس'),
        ),
        migrations.AddField(
            model_name='userpoll',
            name='being_scientific',
            field=models.CharField(choices=[('excellent', 'عالی'), ('good', 'خوب'), ('medium', 'متوسط'), ('weak', 'ضعیف')], max_length=255, null=True, verbose_name='میزان علمی بودن محتوای کلاس أموزشی'),
        ),
        migrations.AddField(
            model_name='userpoll',
            name='final_evaluation',
            field=models.CharField(choices=[('excellent', 'عالی'), ('good', 'خوب'), ('medium', 'متوسط'), ('weak', 'ضعیف')], max_length=255, null=True, verbose_name='ارزیابی پایانی دانشپذیران به طرز درست و صحیح'),
        ),
        migrations.AddField(
            model_name='userpoll',
            name='mastery_of_the_teacher_on_the_subject_of_the_lesson',
            field=models.CharField(choices=[('excellent', 'عالی'), ('good', 'خوب'), ('medium', 'متوسط'), ('weak', 'ضعیف')], max_length=255, null=True, verbose_name='تسلط استاد بر موضوع درس'),
        ),
        migrations.AddField(
            model_name='userpoll',
            name='method_of_expression',
            field=models.CharField(choices=[('excellent', 'عالی'), ('good', 'خوب'), ('medium', 'متوسط'), ('weak', 'ضعیف')], max_length=255, null=True, verbose_name='شیوه بیان، تفهیم و انتقال مطالب درسی'),
        ),
        migrations.AddField(
            model_name='userpoll',
            name='order_and_time',
            field=models.CharField(choices=[('excellent', 'عالی'), ('good', 'خوب'), ('medium', 'متوسط'), ('weak', 'ضعیف')], max_length=255, null=True, verbose_name='نحوه مدیریت کلاس (نظم و زمان)'),
        ),
        migrations.AddField(
            model_name='userpoll',
            name='participation',
            field=models.CharField(choices=[('excellent', 'عالی'), ('good', 'خوب'), ('medium', 'متوسط'), ('weak', 'ضعیف')], max_length=255, null=True, verbose_name='جلب مشارکت و ایجاد انگیزه در مباحث درسی'),
        ),
        migrations.AddField(
            model_name='userpoll',
            name='perform_service',
            field=models.CharField(choices=[('excellent', 'عالی'), ('good', 'خوب'), ('medium', 'متوسط'), ('weak', 'ضعیف')], max_length=255, null=True, verbose_name='انجام خدمت مد نظر توسط کارکنان در زمان مقرر'),
        ),
        migrations.AddField(
            model_name='userpoll',
            name='presentation_of_the_lesson_plan',
            field=models.CharField(choices=[('excellent', 'عالی'), ('good', 'خوب'), ('medium', 'متوسط'), ('weak', 'ضعیف')], max_length=255, null=True, verbose_name='ارئه طرح درس و معرفی منابع و رفرنس های معتبر'),
        ),
        migrations.AddField(
            model_name='userpoll',
            name='projector_quality',
            field=models.CharField(choices=[('excellent', 'عالی'), ('good', 'خوب'), ('medium', 'متوسط'), ('weak', 'ضعیف')], max_length=255, null=True, verbose_name='کیفیت ویدیو پروژکتور، میز و صندلی و وایت برد'),
        ),
        migrations.AddField(
            model_name='userpoll',
            name='quality_of_the_venue',
            field=models.CharField(choices=[('excellent', 'عالی'), ('good', 'خوب'), ('medium', 'متوسط'), ('weak', 'ضعیف')], max_length=255, null=True, verbose_name='کیفیت تهویه، روشنایی و مکان برگزاری'),
        ),
        migrations.AddField(
            model_name='userpoll',
            name='responsiveness',
            field=models.CharField(choices=[('excellent', 'عالی'), ('good', 'خوب'), ('medium', 'متوسط'), ('weak', 'ضعیف')], max_length=255, null=True, verbose_name='اهمیت دادن به پاسخگویی سوالات درسی دانشجویان'),
        ),
        migrations.AddField(
            model_name='userpoll',
            name='social_etiquette_and_behavior',
            field=models.CharField(choices=[('excellent', 'عالی'), ('good', 'خوب'), ('medium', 'متوسط'), ('weak', 'ضعیف')], max_length=255, null=True, verbose_name='آداب و رفتار اجتماعی با دانشجویان و احترام متقابل'),
        ),
        migrations.AddField(
            model_name='userpoll',
            name='teaching_method',
            field=models.CharField(choices=[('excellent', 'عالی'), ('good', 'خوب'), ('medium', 'متوسط'), ('weak', 'ضعیف')], max_length=255, null=True, verbose_name='شیوه تدریس و بکار گیری امکانات کمک آموزشی موجود'),
        ),
        migrations.AddField(
            model_name='userpoll',
            name='way_the_staff_behaves',
            field=models.CharField(choices=[('excellent', 'عالی'), ('good', 'خوب'), ('medium', 'متوسط'), ('weak', 'ضعیف')], max_length=255, null=True, verbose_name='نحوه برخورد کارکنان'),
        ),
    ]
