# Generated by Django 4.0.4 on 2022-06-04 14:04

import Ticket.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('status', models.CharField(choices=[('answered', 'پاسخ داده شده'), ('close', 'بسته'), ('waiting', 'در انتظار')], default='waiting', max_length=40, verbose_name='وضعیت')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('file', models.FileField(blank=True, null=True, upload_to=Ticket.models.file_upload, verbose_name='فایل ضمیمه')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی تیکت',
                'verbose_name_plural': 'دسته بندی تیکت ها',
            },
        ),
        migrations.CreateModel(
            name='TicketAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('file', models.FileField(blank=True, null=True, upload_to=Ticket.models.file_upload, verbose_name='فایل ضمیمه')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Ticket.ticket', verbose_name='پیام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پاسخ های تیکت',
                'verbose_name_plural': 'پاسخ های تیکت ها',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Ticket.ticketcategory', verbose_name='دسته بندی تیکت'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
